version: '3'

services:
  enticai_frontend:
    build: 
      context: ${PWD}/frontend
      dockerfile: Dockerfile.production
    image: enticai_frontend:latest
    container_name: enticai_frontend
    env_file:
      - ${PWD}/frontend/.env.production
    networks:
      - enticai_network
      - enticai_proxy_network

  enticai_backend:
    build: 
      context: ${PWD}/backend
      dockerfile: Dockerfile.production
    volumes:
      - ${PWD}/backend/mongo-certs:/etc/ssl/mongo:ro
    user: "node"
    image: enticai_backend:latest
    container_name: enticai_backend
    env_file:
      - ${PWD}/backend/.env.production
    networks:
      - enticai_network
      - enticai_proxy_network
      - monitoring_network

networks:
  enticai_network:
    external: true
  enticai_proxy_network:
    external: true
  monitoring_network:
    external: true